<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260701231823 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE audit_logs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(50) NOT NULL, resource_type VARCHAR(100) NOT NULL, resource_id INT DEFAULT NULL, description TEXT DEFAULT NULL, ip_address VARCHAR(45) DEFAULT NULL, user_agent VARCHAR(500) DEFAULT NULL, http_method VARCHAR(20) DEFAULT NULL, endpoint VARCHAR(500) DEFAULT NULL, old_values JSON DEFAULT NULL, new_values JSON DEFAULT NULL, status VARCHAR(20) NOT NULL, error_message TEXT DEFAULT NULL, metadata JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D62F2858A76ED395 ON audit_logs (user_id)');
        $this->addSql('CREATE TABLE database_connections (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description VARCHAR(500) DEFAULT NULL, type VARCHAR(20) NOT NULL, host VARCHAR(255) NOT NULL, port INT NOT NULL, database VARCHAR(255) NOT NULL, username VARCHAR(255) NOT NULL, encrypted_password TEXT NOT NULL, advanced_options JSON NOT NULL, active BOOLEAN NOT NULL, tested BOOLEAN NOT NULL, last_tested_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_connection_name ON database_connections (name)');
        $this->addSql('CREATE TABLE local_user_permissions (local_user_id INT NOT NULL, permission_id INT NOT NULL, PRIMARY KEY (local_user_id, permission_id))');
        $this->addSql('CREATE INDEX IDX_30FC5F93ABBD618 ON local_user_permissions (local_user_id)');
        $this->addSql('CREATE INDEX IDX_30FC5F9FED90CCA ON local_user_permissions (permission_id)');
        $this->addSql('CREATE TABLE permissions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(100) NOT NULL, description VARCHAR(500) DEFAULT NULL, scope VARCHAR(50) NOT NULL, category VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_permission_code ON permissions (code)');
        $this->addSql('CREATE TABLE roles (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, description VARCHAR(500) DEFAULT NULL, scope VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_role_name ON roles (name)');
        $this->addSql('CREATE TABLE role_permissions (role_id INT NOT NULL, permission_id INT NOT NULL, PRIMARY KEY (role_id, permission_id))');
        $this->addSql('CREATE INDEX IDX_1FBA94E6D60322AC ON role_permissions (role_id)');
        $this->addSql('CREATE INDEX IDX_1FBA94E6FED90CCA ON role_permissions (permission_id)');
        $this->addSql('CREATE TABLE role_inheritance (role_id INT NOT NULL, parent_role_id INT NOT NULL, PRIMARY KEY (role_id, parent_role_id))');
        $this->addSql('CREATE INDEX IDX_2852FA18D60322AC ON role_inheritance (role_id)');
        $this->addSql('CREATE INDEX IDX_2852FA18A44B56EA ON role_inheritance (parent_role_id)');
        $this->addSql('ALTER TABLE audit_logs ADD CONSTRAINT FK_D62F2858A76ED395 FOREIGN KEY (user_id) REFERENCES local_users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE local_user_permissions ADD CONSTRAINT FK_30FC5F93ABBD618 FOREIGN KEY (local_user_id) REFERENCES local_users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE local_user_permissions ADD CONSTRAINT FK_30FC5F9FED90CCA FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE role_permissions ADD CONSTRAINT FK_1FBA94E6D60322AC FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE role_permissions ADD CONSTRAINT FK_1FBA94E6FED90CCA FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE role_inheritance ADD CONSTRAINT FK_2852FA18D60322AC FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE role_inheritance ADD CONSTRAINT FK_2852FA18A44B56EA FOREIGN KEY (parent_role_id) REFERENCES roles (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE agent_tokens DROP CONSTRAINT fk_f4bd46a83e030acd');
        $this->addSql('DROP INDEX idx_f4bd46a83e030acd');
        $this->addSql('ALTER TABLE agent_tokens ADD CONSTRAINT FK_F4BD46A83E030ACD FOREIGN KEY (application_id) REFERENCES applications (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F4BD46A83E030ACD ON agent_tokens (application_id)');
        $this->addSql('ALTER TABLE local_users ADD is_global_admin BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE local_users ADD role_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE local_users ADD CONSTRAINT FK_B6539EDD60322AC FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_B6539EDD60322AC ON local_users (role_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE audit_logs DROP CONSTRAINT FK_D62F2858A76ED395');
        $this->addSql('ALTER TABLE local_user_permissions DROP CONSTRAINT FK_30FC5F93ABBD618');
        $this->addSql('ALTER TABLE local_user_permissions DROP CONSTRAINT FK_30FC5F9FED90CCA');
        $this->addSql('ALTER TABLE role_permissions DROP CONSTRAINT FK_1FBA94E6D60322AC');
        $this->addSql('ALTER TABLE role_permissions DROP CONSTRAINT FK_1FBA94E6FED90CCA');
        $this->addSql('ALTER TABLE role_inheritance DROP CONSTRAINT FK_2852FA18D60322AC');
        $this->addSql('ALTER TABLE role_inheritance DROP CONSTRAINT FK_2852FA18A44B56EA');
        $this->addSql('DROP TABLE audit_logs');
        $this->addSql('DROP TABLE database_connections');
        $this->addSql('DROP TABLE local_user_permissions');
        $this->addSql('DROP TABLE permissions');
        $this->addSql('DROP TABLE roles');
        $this->addSql('DROP TABLE role_permissions');
        $this->addSql('DROP TABLE role_inheritance');
        $this->addSql('ALTER TABLE agent_tokens DROP CONSTRAINT FK_F4BD46A83E030ACD');
        $this->addSql('DROP INDEX UNIQ_F4BD46A83E030ACD');
        $this->addSql('ALTER TABLE agent_tokens ADD CONSTRAINT fk_f4bd46a83e030acd FOREIGN KEY (application_id) REFERENCES applications (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_f4bd46a83e030acd ON agent_tokens (application_id)');
        $this->addSql('ALTER TABLE local_users DROP CONSTRAINT FK_B6539EDD60322AC');
        $this->addSql('DROP INDEX IDX_B6539EDD60322AC');
        $this->addSql('ALTER TABLE local_users DROP is_global_admin');
        $this->addSql('ALTER TABLE local_users DROP role_id');
    }
}
